### ISSUE TITLE
Add plain identity test

### ISSUE THREAD

**Issue by pehala** [Kuadrant/testsuite#111]
**Summary**
Implement tests for Identity: Plain

**Documentation**
https://github.com/Kuadrant/authorino/blob/main/docs/features.md#plain-identityplain

**Test Cases**

- [x] Use of Authorino as Kubernetes ValidatingWebhook service (Kubernetes 'userInfo' injected in the body of the AdmissionReview request
- [ ] Concider test case without Webhook Validation.

Won't be done for now: Authentication handled in Envoy leveraging the Envoy JWT Authentication filter (decoded JWT injected as 'metadata_context')

**Comment by mkudlej** [comment]
Kubernetes part of this is covered in https://github.com/Kuadrant/testsuite/issues/89

**Comment by jsmolar** [comment]
Use case described in features doc: "Use of Authorino as Kubernetes ValidatingWebhook service (Kubernetes 'userInfo' injected in the body of the AdmissionReview request): is covered by https://github.com/Kuadrant/testsuite/pull/141

**Comment by jsmolar** [comment]
The second use case `Authentication handled in Envoy leveraging the Envoy JWT Authentication filter (decoded JWT injected as 'metadata_context')` requires Envoy CR modification which is not a valid test case for Kuadrant.
