### ISSUE TITLE
Add test for workload migration

### ISSUE THREAD

**Issue by ficap** [Kuadrant/testsuite#115]
When placement of namespace is changed workload is migrated to another workloadcluster. glbc shall delay deletion of workload on cluster A until it is present and responding on cluster B and new dns record is properly distributed.

**Comment by ficap** [comment]
https://github.com/kcp-dev/kcp-glbc/blob/main/docs/getting_started/tutorial.md#main-use-case

**Comment by pehala** [comment]
No longer valid
