### ISSUE TITLE
Improve HF agents configuration from testsuite

### ISSUE THREAD

**Issue by dhlavac** [Kuadrant/testsuite#162]
**Summary**

Currently are HF agents configured automatically from test-specific fixtures. In some cases, it is needed to add extra options for agents. The goal of this issue is to extend current behavior to contain also extra agents options.

**Documentation**

Similar implementation as used in 3scale tests -> https://github.com/3scale-qe/3scale-tests/tree/main/testsuite/tests/performance

**Comment by pehala** [comment]
Not needed in a reasonable future
