### ISSUE TITLE
Add OPA/Rego test

### ISSUE THREAD

**Issue by pehala** [Kuadrant/testsuite#2]
- https://github.com/Kuadrant/authorino/blob/main/docs/user-guides/opa-authorization.md
- https://www.openpolicyagent.org/docs/latest/
- https://www.openpolicyagent.org/docs/latest/#rego

- [x] Test for inline rego
- [x] Test for external rego
- [ ] Test for external precompiled rego (including invalid byte code)
- [x] Test for external rego with unaccepted content-type

**Comment by jsmolar** [comment]
Test for unaccepted content type is not required

**Comment by pehala** [comment]
I believe I do, as far as I know, you can pass precompiled Rego policy instead of a string and this was mean to test code injection or other type of attack that can be done if Authorino accepts byte-code directly. Please try it out and if it no longer works we can remove it

**Comment by azgabur** [comment]
This feature does not exist so it can not be tested. Confirmed by in slack https://kubernetes.slack.com/archives/C05J0D0V525/p1720006911930289?thread_ts=1719999649.929929&cid=C05J0D0V525

All other test cases were already implemented so I am closing this issue as Done.
