### ISSUE TITLE
Add test for adding and removing listeners to/from Gateway when DNSPolicy and TLSPolicy are attached

### ISSUE THREAD

**Issue by ficap** [Kuadrant/testsuite#308]
**Summary**
When adding or removing listeners to/from  a Gateway (possibly with various hostnames) with attached DNSPolicy and/or TLSPolicy, certs/dns records should be updated accordingly.

**Documentation**

Link any relevant product documentation.

**Test cases**

Split test case into sub-tasks if needed. It should help with tracking progress and navigating more complex tasks.

**Comment by ficap** [comment]
related bug: https://github.com/Kuadrant/multicluster-gateway-controller/issues/601

**Comment by azgabur** [comment]
New issue for the related bug: https://github.com/Kuadrant/kuadrant-operator/issues/794
