### ISSUE TITLE
Add ttl test for authentication jwt verification

### ISSUE THREAD

**Issue by azgabur** [Kuadrant/testsuite#314]
**Summary**

Authorino by default does not refresh JWKS from OIDC endpoint but can be set to do so in regular intervals by using a `ttl` variable.

**Documentation**

https://github.com/Kuadrant/authorino/blob/main/docs/features.md#jwt-verification-authenticationjwt

**Test cases**

- [x] Implement `ttl` functionality. Done in #313 
- [ ] Test for refreshing JWKS
- [ ] Add a testcase in test_dinosaur

**Comment by trepel** [comment]
Intentionally not added to dinosaur because this would introduce code duplication.
