### ISSUE TITLE
Atomic defaults tests

### ISSUE THREAD

**Issue by martinhesko** [Kuadrant/testsuite#375]
**Summary**

The kuadrant operator now allows defaults to be set for AuthPolicy and RateLimitPolicy. Test that these defaults work properly and are mutually exclusive with setting policy in spec.

**Documentation**

Implementing PRs: https://github.com/Kuadrant/kuadrant-operator/pull/503, https://github.com/Kuadrant/kuadrant-operator/pull/456, https://github.com/Kuadrant/kuadrant-operator/pull/536
RFC: https://github.com/Kuadrant/architecture/blob/main/rfcs/0009-defaults-and-overrides.md

**Test cases**

Repeat each for AuthPolicy and RateLimitPolicy

* Tests functionality of rules set within the `defaults` block
    - Set HTTPRoute attached policy with an explicit defaults block
    - verify the policy inside the defaults block functions as a normal policy
 
* Test mutual exclusivity of `defaults` block with other rules
    - set HTTPRoute attached policy configured both with regular config and config inside a `defaults` block
    - Check that policy is rejected due to `Implicit and explicit defaults are mutually exclusive`

* Test policy inheritability and PolicyAffected condition
    -  Attach a policy with a configured `defaults` block to your gateway
    - Check the status of the gateway's HTTPRoute
    - status should specify `Object affected by {Auth|RateLimit}Policy x`
    - Curl the route to verify the policy attached to gateway got applied to your HTTPRoute

* Test policy discoverability
    -  Attach a policy with a configured `defaults` block to your gateway
    - Create a new HTTPRoute attached to your gateway
    - Check HTTPRoute status, it should specify `Object affected by {Auth|RateLimit}Policy x`
    - Curl the route to verify the policy attached to gateway got applied to your HTTPRoute

**Comment by averevki** [comment]
@martinhesko how do 2 last test cases differ from each other?
